import {
    Home,
    Classify,
    SmallMBook,
    Cart,
    Main,
    Login,
    Register,
    ClassifyLeft,
    ClassifyRight,
    Recommend,
    Collect,
    Appraisal,
    Video,
    GoodList,
    Details,       
    Brand,
    Search,
    Quanbu
} from "@/pages";

export const TabBarRoute = [
    {
        path:"/home",
        component:Home,
        meta:{
            flag:true
        },
        text:"精选",
        icon:"\ue642"
    },
   
    {
        path:"/classify",
        component:Classify,
        meta:{
            flag:true
        },
        text:"分类",
        icon:"\ue601",
        children:[
            {
                path:"/classify/classifyLeft",
                component:ClassifyLeft,
                meta:{
                    flag:true
                },
            },
            {
                path:"/classify/classifyRight",
                component:ClassifyRight,
                meta:{
                    flag:true
                },
            }
        ]
    },
    {
        path:"/smallMBook",
        component:SmallMBook,
        meta:{
            flag:true
        },
        text:"小萌书",
        icon:"\ue600",
        children:[
            {
                path:"/smallMBook/recommend",
                component:Recommend,
                meta:{
                    flag:true
                },
                text:"小萌书",
                icon:"\ue600"
            },
            {
                path:"/smallMBook/collect",
                component:Collect,
                meta:{
                    flag:true
                },
                text:"小萌书",
                icon:"\ue600"
            },
            {
                path:"/smallMBook/appraisal",
                component:Appraisal,
                meta:{
                    flag:true
                },
                text:"小萌书",
                icon:"\ue600"
            },
            {
                path:"/smallMBook/video",
                component:Video,
                meta:{
                    flag:true
                },
                text:"小萌书",
                icon:"\ue600"
            }
        ]
    },
    {
        path:"/cart",
        component:Cart,
        meta:{
            flag:false
        },
        text:"购物车",
        icon:"\ue657"
    },
    {
        path:"/main",
        component:Main,
        meta:{
            flag:true
        },
        text:"我的",
        icon:"\ue614"
    }
]

export const NoTabBarRoute = [
    {
        path:"/search",
        component:Search,
        meta:{
            flag:true
        },
        text:"精选",
        icon:"\ue642" 
    },
    {
        path:"/quanbu",
        component:Quanbu,
        meta:{
            flag:true
        },
        text:"精选",
        icon:"\ue642" 
    },
    {
        path:"/login",
        component:Login,
        meta:{
            flag:false
        },
        text:"登录"
    },
    {
        path:"/register",
        component:Register,
        meta:{
            flag:false
        },
        text:"注册"
    },
    {
        path:"/goodList/:id_param/:xxs",
        component:GoodList,
        meta:{
            flag:false
        },
        text:"商品列表"
    },
    {
        path:"/details/:gid/:sale_price/:market_price",
        component:Details,
        meta:{
            flag:false
        },
        text:"商品详情"
    },
    {
        path:"/brand/:gid",
        component:Brand,
        meta:{
            flag:false
        },
        text:"品牌"
    }
]

export const RouteConfig = TabBarRoute.concat(NoTabBarRoute)